version: '3'
services:
  mariadb-server:
    image: mysql:latest
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: abcXYZ123$
      MYSQL_ROOT_HOST: '%'
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak_user
      MYSQL_PASSWORD: xyz123ABC
      MYSQL_INITDB_SKIP_TZINFO: '1'
      MYSQL_SSL_MODE: 'DISABLED'
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - mariadb-server-vol:/var/lib/mysql
    networks:
      - demo-network

  phpMyAdmin:
    image: phpmyadmin/phpmyadmin:latest
    depends_on:
      - mariadb-server
    environment:
      PMA_HOST: mariadb-server
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - 8180:80
    networks:
      - demo-network

  start_dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - phpMyAdmin
    command: mariadb-server:3306
    networks:
      - demo-network

  keycloak:
    image: jboss/keycloak  
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: MYSQL
      DB_ADDR: mariadb-server
      DB_DATABASE: keycloak
      DB_USER: keycloak_user
      DB_PASSWORD: xyz123ABC
    depends_on:
      - mariadb-server
    networks:
      - demo-network

networks:
  demo-network:

volumes:
  mariadb-server-vol:
